import type { ArtifactItem } from "@/lib/types";

export const artifacts: ArtifactItem[] = [
  {
    key: "textbook-evidence",
    kind: "textbook_evidence",
    title: "教材",
    status: "approved",
    summary: "人教版二年级上册，第七单元表内乘法（一）。",
    updatedAt: "今天 10:24",
    reusable: true,
    sourceTitles: ["项目配置"],
    previewFields: [
      { label: "教材版本", value: "人教版二年级上册" },
      { label: "单元", value: "第七单元 表内乘法（一）" },
      { label: "知识点", value: "乘法意义、口诀初步、情境表达" },
    ],
    actions: { canCopy: true, canUseAsInput: true, canOpenDetail: true, canConfirm: false, canRegenerate: true },
    content: {
      "证据摘要": "教材通过真实数量情境引出乘法，适合从重复加法过渡到乘法表达。",
      "关键页码": ["主题图：乘法情境", "例题：几个几", "练习：口诀初步"],
    },
  },
  {
    key: "lesson-plan",
    kind: "lesson_plan",
    title: "教案",
    status: "approved",
    summary: "教学目标、教学流程、课堂练习和板书设计已确认。",
    updatedAt: "今天 10:24",
    reusable: true,
    sourceTitles: ["教材"],
    previewFields: [
      { label: "教学目标", value: "理解几个几可以用乘法表示。" },
      { label: "重难点", value: "从加法情境抽象成乘法算式。" },
      { label: "板书", value: "几个几 -> 加法 -> 乘法" },
    ],
    actions: { canCopy: true, canUseAsInput: true, canOpenDetail: true, canConfirm: false, canRegenerate: true },
    content: {
      "教学流程": "情境观察、数量表达、算式转换、口诀初步、练习迁移。",
      "板书设计": "3 个 2 相加：2+2+2=6，也可以写作 3x2=6。",
    },
  },
  {
    key: "intro-video-plan",
    kind: "intro_video_plan",
    title: "导入",
    status: "approved",
    summary: "使用情境问题连接课堂，不提前讲乘法结论。",
    updatedAt: "今天 10:24",
    reusable: true,
    sourceTitles: ["教案"],
    previewFields: [
      { label: "独立主题", value: "游乐场里的重复队列" },
      { label: "开场钩子", value: "每辆小车坐 2 人，来了 4 辆车，一共有多少人？" },
      { label: "课程锚点", value: "重复出现的相同数量，引出几个几。" },
    ],
    actions: { canCopy: true, canUseAsInput: true, canOpenDetail: true, canConfirm: true, canRegenerate: true },
    content: {
      "课堂落点": "视频只提出数量问题，结论留在课堂里通过学生表达完成。",
    },
  },
  {
    key: "ppt-draft",
    kind: "ppt_draft",
    title: "PPT",
    status: "in_progress",
    summary: "12 页，已生成 8 页，来自已确认教案与导入锚点。",
    updatedAt: "生成中",
    reusable: false,
    sourceTitles: ["教案", "导入"],
    previewFields: [
      { label: "页数", value: "12 页，已生成 8 页" },
      { label: "页面内容", value: "封面、学习目标、情境导入、练习巩固" },
      { label: "主视觉", value: "低年级数学情境插画与数量分组" },
    ],
    actions: { canCopy: false, canUseAsInput: false, canOpenDetail: true, canConfirm: false, canRegenerate: false },
    content: {
      "逐页摘要": "第 1 页封面；第 2 页学习目标；第 3-6 页情境导入；第 7-12 页练习与板书。",
    },
  },
  {
    key: "image-prompts",
    kind: "image_prompts",
    title: "图片",
    status: "not_started",
    summary: "等待 PPT 草稿确认后生成图片提示词。",
    updatedAt: "尚未开始",
    reusable: false,
    sourceTitles: ["PPT"],
    previewFields: [
      { label: "用途", value: "PPT 主视觉、角色图、导入视频参考图" },
      { label: "画幅", value: "16:9 和 4:3" },
    ],
    actions: { canCopy: false, canUseAsInput: false, canOpenDetail: true, canConfirm: false, canRegenerate: false },
    content: { "示例用途": "PPT 主视觉、课堂任务角色、导入视频首帧参考图。" },
  },
  {
    key: "video-storyboard",
    kind: "video_storyboard",
    title: "视频",
    status: "not_started",
    summary: "等待导入方案与图片资产确认后生成视频分镜。",
    updatedAt: "尚未开始",
    reusable: false,
    sourceTitles: ["导入", "图片"],
    previewFields: [
      { label: "预计内容", value: "镜头编号、时长、画面主体、旁白切片" },
      { label: "状态", value: "尚未进入生成" },
    ],
    actions: { canCopy: false, canUseAsInput: false, canOpenDetail: true, canConfirm: false, canRegenerate: false },
    content: { "生成说明": "确认图片资产后再生成分镜和视频提示词。" },
  },
  {
    key: "final-delivery",
    kind: "final_delivery",
    title: "交付",
    status: "not_started",
    summary: "将汇总教案、PPT、导入视频、讲稿和检查清单。",
    updatedAt: "尚未开始",
    reusable: false,
    sourceTitles: ["教案", "PPT", "视频"],
    previewFields: [{ label: "交付内容", value: "教案、PPT、导入视频、讲稿、检查清单" }],
    actions: { canCopy: false, canUseAsInput: false, canOpenDetail: true, canConfirm: false, canRegenerate: false },
    content: { "交付包": "完成后集中展示教案、PPT、导入视频、讲稿和检查清单。" },
  },
];

