import type { CapabilityDefinition, CapabilityId } from "./types";

const capabilityDefinitions: CapabilityDefinition[] = [
  {
    id: "requirement_spec",
    userLabel: "整理备课需求",
    description: "把教师自然输入整理成可确认的备课需求规格。",
    inputSchema: { required: ["teacherGoal"] },
    outputSchema: { artifact: "requirement_spec" },
    upstreamCapabilities: [],
    artifactKind: "requirement_spec",
    workflowNodeKey: "requirement_spec",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "需求整理暂时没有完成，可以补充年级、课题后重试。",
    },
  },
  {
    id: "lesson_plan",
    userLabel: "生成公开课教案",
    description: "基于已确认需求和教材依据生成公开课教案。",
    inputSchema: { required: ["requirement_spec"] },
    outputSchema: { artifact: "lesson_plan" },
    upstreamCapabilities: ["requirement_spec"],
    artifactKind: "lesson_plan",
    workflowNodeKey: "lesson_plan",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "教案暂时没有生成成功，可以先检查需求规格后重试。",
    },
  },
  {
    id: "ppt_outline",
    userLabel: "生成 PPT 大纲",
    description: "生成 PPT 页面任务规划、逐页教学动作和课堂呈现建议。",
    inputSchema: { required: ["teacherGoal"] },
    outputSchema: { artifact: "ppt_draft" },
    upstreamCapabilities: ["requirement_spec"],
    artifactKind: "ppt_draft",
    workflowNodeKey: "ppt_draft",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "PPT 大纲暂时没有生成成功，可以先确认需求后重试。",
    },
  },
  {
    id: "ppt_design",
    userLabel: "生成 PPT 设计稿",
    description: "把 PPT 大纲转成逐页四层设计稿，明确底图、元素、文字和排版。",
    inputSchema: { required: ["ppt_outline"] },
    outputSchema: { artifact: "ppt_design_draft" },
    upstreamCapabilities: ["ppt_outline"],
    artifactKind: "ppt_design_draft",
    workflowNodeKey: "ppt_design_draft",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "PPT 设计稿暂时没有生成成功，可以先检查 PPT 大纲后重试。",
    },
  },
  {
    id: "coze_ppt",
    userLabel: "生成 PPTX 文件",
    description: "只基于逐页四层 PPT 设计稿调用外部能力生成可下载 PPTX。",
    inputSchema: { required: ["ppt_design_draft"] },
    outputSchema: { artifact: "pptx_artifact" },
    upstreamCapabilities: ["ppt_design"],
    artifactKind: "pptx_artifact",
    workflowNodeKey: "pptx_artifact",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
    userMessage: "PPTX 生成服务暂时不可用，可以稍后重试，或先继续修改 PPT 设计稿。",
    },
  },
  {
    id: "ppt_sample_assets",
    userLabel: "生成 PPT 关键样张资产批次",
    description: "根据已确认的逐页质量设计包生成关键场景和透明小素材，并形成逐对象来源清单。",
    inputSchema: { required: ["ppt_design_draft"] },
    outputSchema: { artifact: "image_prompts", realAsset: "image_bundle" },
    upstreamCapabilities: ["ppt_design"],
    artifactKind: "image_prompts",
    workflowNodeKey: "image_prompts",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "PPT 样张资产批次暂时没有完成，可以先检查样张页和素材计划后重试。",
    },
  },
  {
    id: "ppt_key_samples",
    userLabel: "组装 PPT 关键样张",
    description: "使用已确认的逐页设计和真实资产组装可编辑样张，渲染逐页预览与三份独立总览，等待 D/V/P 审查。",
    inputSchema: { required: ["ppt_design_draft", "image_prompts"] },
    outputSchema: { artifact: "image_prompts", realAsset: "pptx_and_render_bundle" },
    upstreamCapabilities: ["ppt_design", "ppt_sample_assets"],
    artifactKind: "image_prompts",
    workflowNodeKey: "image_prompts",
    requiresConfirmation: true,
    providerMode: "package",
    deterministicFallback: "allowed",
    failureRecovery: {
      retryable: true,
      userMessage: "PPT 关键样张暂时没有组装完成，可以先检查设计稿和样张资产后重试。",
    },
  },
  {
    id: "ppt_full_deck",
    userLabel: "组装完整可编辑 PPT",
    description: "使用当前样张批准、完整真实资产和逐页设计组装完整 PPTX，并生成 PDF、逐页预览和总览等待交付审查。",
    inputSchema: { required: ["ppt_design_draft", "image_prompts"] },
    outputSchema: { artifact: "pptx_artifact", realAsset: "pptx_pdf_render_bundle" },
    upstreamCapabilities: ["ppt_design", "ppt_full_assets"],
    artifactKind: "pptx_artifact",
    workflowNodeKey: "pptx_artifact",
    requiresConfirmation: true,
    providerMode: "package",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "完整 PPT 暂时没有组装完成，可以先检查样张批准、全量资产和逐页设计。",
    },
  },
  {
    id: "ppt_page_repair",
    userLabel: "返修指定课件页面",
    description: "只修改教师明确指定的课件页面，保留其他页面素材和审查证据。",
    inputSchema: { required: ["pptx_artifact", "ppt_design_draft", "image_prompts"] },
    outputSchema: { artifact: "pptx_artifact", realAsset: "pptx_pdf_render_bundle" },
    upstreamCapabilities: ["ppt_full_deck", "ppt_design", "ppt_full_assets"],
    artifactKind: "pptx_artifact",
    workflowNodeKey: "pptx_artifact",
    requiresConfirmation: true,
    providerMode: "package",
    deterministicFallback: "blocked",
    failureRecovery: { retryable: true, userMessage: "指定页面暂时没有返修完成，可以检查页面要求后重试。" },
  },
  {
    id: "ppt_full_assets",
    userLabel: "生成 PPT 全量正式资产",
    description: "在当前关键样张获得明确批准后，为全部页面生成正式场景和透明小素材，并形成完整来源清单。",
    inputSchema: { required: ["ppt_design_draft", "image_prompts"] },
    outputSchema: { artifact: "image_prompts", realAsset: "full_image_bundle" },
    upstreamCapabilities: ["ppt_design", "ppt_key_samples"],
    artifactKind: "image_prompts",
    workflowNodeKey: "image_prompts",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "PPT 全量正式资产暂时没有生成完成，可以先检查当前样张批准和逐页素材计划。",
    },
  },
  {
    id: "image_asset",
    userLabel: "生成课堂图片素材",
    description: "根据课堂场景生成图片素材。",
    inputSchema: { required: ["ppt_draft"] },
    outputSchema: { artifact: "image_prompts", realAsset: "image" },
    upstreamCapabilities: ["ppt_outline"],
    artifactKind: "image_prompts",
    workflowNodeKey: "image_prompts",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "图片生成暂时不可用，可以先保留图片提示词后重试。",
    },
  },
  {
    id: "intro_video",
    userLabel: "生成导入视频素材",
    description: "根据导入方案和分镜生成课堂导入视频素材。",
    inputSchema: { required: ["introVideoPlan"] },
    outputSchema: { artifact: "video_storyboard", realAsset: "video" },
    upstreamCapabilities: ["ppt_design"],
    artifactKind: "video_storyboard",
    workflowNodeKey: "video_storyboard",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "视频生成暂时不可用，可以先继续完善导入方案。",
    },
  },
  {
    id: "knowledge_anchor_extract",
    userLabel: "提取视频知识锚点",
    description: "从结构化教案中提取导入视频必须回到的关键知识、易错点和课堂问题。",
    inputSchema: { required: ["lesson_plan"] },
    outputSchema: { artifact: "knowledge_anchor_extract" },
    upstreamCapabilities: ["lesson_plan"],
    artifactKind: "knowledge_anchor_extract",
    workflowNodeKey: "knowledge_anchor_extract",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "知识锚点暂时没有提取完成，可以先检查教案结构后重试。",
    },
  },
  {
    id: "creative_theme_generate",
    userLabel: "生成导入创意主题",
    description: "围绕知识锚点生成多个课堂导入创意主题，避免直接讲完知识结论。",
    inputSchema: { required: ["knowledge_anchor_extract"] },
    outputSchema: { artifact: "creative_theme_generate" },
    upstreamCapabilities: ["knowledge_anchor_extract"],
    artifactKind: "creative_theme_generate",
    workflowNodeKey: "creative_theme_generate",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "创意主题暂时没有生成完成，可以先确认知识锚点后重试。",
    },
  },
  {
    id: "video_script_generate",
    userLabel: "生成导入视频脚本",
    description: "基于已确认创意主题生成视频脚本、旁白或字幕和课堂边界约束。",
    inputSchema: { required: ["creative_theme_generate"] },
    outputSchema: { artifact: "video_script_generate" },
    upstreamCapabilities: ["creative_theme_generate"],
    artifactKind: "video_script_generate",
    workflowNodeKey: "video_script_generate",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "视频脚本暂时没有生成完成，可以先确认导入主题后重试。",
    },
  },
  {
    id: "storyboard_generate",
    userLabel: "生成视频分镜",
    description: "把视频脚本拆成分镜，写清每镜头时长、画面动作、镜头运动、资产和连续性要求。",
    inputSchema: { required: ["video_script_generate"] },
    outputSchema: { artifact: "storyboard_generate" },
    upstreamCapabilities: ["video_script_generate"],
    artifactKind: "storyboard_generate",
    workflowNodeKey: "storyboard_generate",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "视频分镜暂时没有生成完成，可以先检查脚本后重试。",
    },
  },
  {
    id: "asset_brief_generate",
    userLabel: "生成视频资产说明",
    description: "为分镜生成统一风格、角色、道具、场景和关键帧资产说明。",
    inputSchema: { required: ["storyboard_generate"] },
    outputSchema: { artifact: "asset_brief_generate" },
    upstreamCapabilities: ["storyboard_generate"],
    artifactKind: "asset_brief_generate",
    workflowNodeKey: "asset_brief_generate",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "资产说明暂时没有生成完成，可以先检查分镜后重试。",
    },
  },
  {
    id: "asset_image_generate",
    userLabel: "生成视频资产图",
    description: "根据资产说明生成统一风格图、角色参考图、道具参考图、场景参考图和关键帧图。",
    inputSchema: { required: ["asset_brief_generate"] },
    outputSchema: { artifact: "asset_image_generate", realAsset: "image" },
    upstreamCapabilities: ["asset_brief_generate"],
    artifactKind: "asset_image_generate",
    workflowNodeKey: "asset_image_generate",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "视频资产图暂时没有生成成功，可以先保留资产说明后重试。",
    },
  },
  {
    id: "video_segment_plan",
    userLabel: "规划分镜视频片段",
    description: "基于分镜和资产图规划每段视频生成输入、参考图、目标时长和失败重试边界。",
    inputSchema: { required: ["storyboard_generate", "asset_image_generate"] },
    outputSchema: { artifact: "video_segment_plan" },
    upstreamCapabilities: ["storyboard_generate", "asset_image_generate"],
    artifactKind: "video_segment_plan",
    workflowNodeKey: "video_segment_plan",
    requiresConfirmation: true,
    providerMode: "internal",
    deterministicFallback: "draft_only",
    failureRecovery: {
      retryable: true,
      userMessage: "分镜视频计划暂时没有生成完成，可以先检查分镜和资产图后重试。",
    },
  },
  {
    id: "video_segment_generate",
    userLabel: "生成分镜视频片段",
    description: "只在分镜、资产图和片段计划齐全后调用视频能力生成单段视频。",
    inputSchema: { required: ["video_segment_plan", "storyboard_generate", "asset_image_generate"] },
    outputSchema: { artifact: "video_segment_generate", realAsset: "video" },
    upstreamCapabilities: ["video_segment_plan", "storyboard_generate", "asset_image_generate"],
    artifactKind: "video_segment_generate",
    workflowNodeKey: "video_segment_generate",
    requiresConfirmation: true,
    providerMode: "external",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "分镜视频片段暂时没有生成成功，可以只重试失败片段。",
    },
  },
  {
    id: "concat_only_assemble",
    userLabel: "只拼接最终导入视频",
    description: "只按分镜顺序拼接已通过校验的片段，不重排、不加转场、不加滤镜、不重写内容。",
    inputSchema: { required: ["video_segment_generate", "storyboard_generate", "video_script_generate"] },
    outputSchema: { artifact: "concat_only_assemble", realAsset: "video" },
    upstreamCapabilities: ["video_segment_generate", "storyboard_generate", "video_script_generate"],
    artifactKind: "concat_only_assemble",
    workflowNodeKey: "concat_only_assemble",
    requiresConfirmation: true,
    providerMode: "package",
    deterministicFallback: "blocked",
    failureRecovery: {
      retryable: true,
      userMessage: "最终视频暂时没有拼接完成，可以检查分镜片段后重试。",
    },
  },
  {
    id: "final_package",
    userLabel: "打包最终交付",
    description: "把已确认的教案、PPT、图片、视频和交付说明打包。",
    inputSchema: { required: ["approvedArtifacts"] },
    outputSchema: { artifact: "final_package" },
    upstreamCapabilities: ["requirement_spec", "lesson_plan", "ppt_design", "coze_ppt", "image_asset", "video_script_generate", "concat_only_assemble"],
    artifactKind: "final_delivery",
    workflowNodeKey: "final_delivery",
    requiresConfirmation: true,
    providerMode: "package",
    deterministicFallback: "allowed",
    failureRecovery: {
      retryable: true,
      userMessage: "最终交付包暂时没有打包成功，可以检查已确认成果后重试。",
    },
  },
];

export function getCapabilityDefinitions(): CapabilityDefinition[] {
  return capabilityDefinitions.map((definition) => ({ ...definition }));
}

export function getCapabilityDefinition(id: CapabilityId): CapabilityDefinition {
  const definition = capabilityDefinitions.find((capability) => capability.id === id);
  if (!definition) {
    throw new Error(`Unknown capability: ${id}`);
  }
  return { ...definition };
}
